// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset.sql

package database

import (
	"context"
)

const resetRefreshTokens = `-- name: ResetRefreshTokens :exec
DELETE FROM refresh_tokens
`

func (q *Queries) ResetRefreshTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetRefreshTokens)
	return err
}

const resetUsers = `-- name: ResetUsers :exec
DELETE FROM users
`

func (q *Queries) ResetUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUsers)
	return err
}
