// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const changeActiveApp = `-- name: ChangeActiveApp :one
UPDATE users SET active_app = $2, updated_at = NOW()
WHERE username = $1
RETURNING id, created_at, updated_at, username, hashed_password, deleted_at, active_app
`

type ChangeActiveAppParams struct {
	Username  string
	ActiveApp sql.NullString
}

func (q *Queries) ChangeActiveApp(ctx context.Context, arg ChangeActiveAppParams) (User, error) {
	row := q.db.QueryRowContext(ctx, changeActiveApp, arg.Username, arg.ActiveApp)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.HashedPassword,
		&i.DeletedAt,
		&i.ActiveApp,
	)
	return i, err
}

const checkUserByName = `-- name: CheckUserByName :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) CheckUserByName(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserByName, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, username, hashed_password)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
    )
RETURNING id, created_at, updated_at, username, hashed_password, deleted_at, active_app
`

type CreateUserParams struct {
	Username       string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.HashedPassword,
		&i.DeletedAt,
		&i.ActiveApp,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
UPDATE users SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, username, hashed_password, deleted_at, active_app
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.HashedPassword,
		&i.DeletedAt,
		&i.ActiveApp,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, username, hashed_password, deleted_at, active_app FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.HashedPassword,
		&i.DeletedAt,
		&i.ActiveApp,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created_at, updated_at, username, hashed_password, deleted_at, active_app FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.HashedPassword,
		&i.DeletedAt,
		&i.ActiveApp,
	)
	return i, err
}
